#!/usr/bin/env bash
# Configures /etc/hosts to redirect localhost and facebook.com

sed 's/127.0.0.1/127.0.0.2/g' /etc/hosts > /tmp/hosts_temp
echo "8.8.8.8 facebook.com" >> /tmp/hosts_temp
cat /tmp/hosts_temp > /etc/hosts
rm -f /tmp/hosts_temp
